import React from "react"
import Layout from "../components/layout"
import SEO from "../components/seo"
import ProjectCard from "../components/ProjectCard"
import Layouts from "../components/Layouts"

export default function Portfolio() {
  const projects = [
    {
      name: "Geepitee",
      description:
        "Geepitee, the ultimate app for creating and managing super prompts for ChatGPT through the OpenAI API. Our user-friendly platform allows you to craft your own super prompts and switch between different roles with ease. (All this description was generated by Geepitee itself!)",
      url: "https://www.geepitee.com",
    },
    {
      name: "Retro Time App",
      description:
        "App to run Retrospective meetings for teams working remotely. It was implemented with React and Firebase services: Cloud Firestore DB and Firebase Auth",
      url: "https://retrotime.app",
    },
    {
      name: "Machine Learning: Gestures Recognition",
      description:
        "Concept idea of navigating a website with your hands gestures. This was a project for a Hackweek in Bluedot. It was built with TensorFlow.js and React",
      url: "https://gestures-recognition.web.app/",
    },
  ]

  return (
    <Layout>
      <SEO title="Portfolio" />
      <h1>Portfolio</h1>
      <Layouts.TwoColumns>
        {projects.map(project => (
          <ProjectCard
            title={project.name}
            description={project.description}
            url={project.url}
          />
        ))}
      </Layouts.TwoColumns>
    </Layout>
  )
}
